#!/usr/bin/env bash

PROJECT_ID=$1
[[ -z "$PROJECT_ID" ]] && echo "error: require new project ID" && exit 1

gcloud beta deployment-manager --project $PROJECT_ID type-providers create dataflow --api-options-file=options.yaml --descriptor-url="https://dataflow.googleapis.com/\$discovery/rest?version=v1b3"