#!/usr/bin/env bash

PROJECT_ID=$1
[[ -z "$PROJECT_ID" ]] && echo "error: require project ID" && exit 1

if ! gcloud projects list | awk '{ print $1 }' | grep -Eq "^${PROJECT_ID}$" ; then
  echo "error: invalid project ID" && exit 1
fi

SERVICE_ACCOUNT_ID="pubsub-publish-sa"
DESCRIPTION="Used within AWS Lambda to publish to PubSub"
DISPLAY_NAME="PubSub publisher"

while [[ -n "$1" ]] ; do
  case $1 in
  --pubsub)
    ROLE="roles/pubsub.publisher"
    ;;
  esac
shift
done

[[ -z "$ROLE" ]] && echo "error: invalid role" && exit 1

gcloud iam service-accounts create "$SERVICE_ACCOUNT_ID" \
    --description="$DESCRIPTION" \
    --display-name="$DISPLAY_NAME"

gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:${SERVICE_ACCOUNT_ID}@${PROJECT_ID}.iam.gserviceaccount.com" \
    --role="$ROLE"