#!/usr/bin/env bash

DESCRIPTION=""
roles=()

while [[ -n "$1" ]]; do
  case $1 in
  --name)
    NAME="$2"
    shift
    ;;
  --project)
    PROJECT_ID="$2"
    shift
    ;;
  --key)
    KEY="true"
    ;;
  --description)
    DESCRIPTION="$2"
    shift
    ;;
  --pubsub)
    roles=("${roles[@]}" "roles/pubsub.publisher")
    ;;
  --compute)
    roles=("${roles[@]}" "roles/logging.logWriter" "roles/monitoring.metricWriter" "roles/cloudtrace.agent")
    ;;
  --container)
    roles=("${roles[@]}" "roles/containerregistry.ServiceAgent")
    ;;
  --storage)
    roles=("${roles[@]}" "roles/storage.objectViewer")
    roles=("${roles[@]}" "roles/storage.objectCreator")
    ;;
  --storage-read)
    roles=("${roles[@]}" "roles/storage.objectViewer")
    ;;
  --storage-write)
    roles=("${roles[@]}" "roles/storage.objectCreator")
    ;;
  --storage-admin)
    roles=("${roles[@]}" "roles/storage.objectAdmin")
    ;;
  --dataflow)
    roles=("${roles[@]}" "roles/dataflow.admin")
    ;;
  --datastore)
    roles=("${roles[@]}" "roles/datastore.user")
    roles=("${roles[@]}" "roles/datastore.importExportAdmin")
    ;;
  --bigquery-user)
    roles=("${roles[@]}" "roles/bigquery.dataViewer" "roles/bigquery.user")
    ;;
  --bigquery-agent)
    roles=("${roles[@]}" "roles/bigquery.dataEditor")
    ;;
  --redis)
    roles=("${roles[@]}" "roles/redis.editor")
    ;;
  --secrets)
    roles=("${roles[@]}" "roles/secretmanager.secretAccessor")
    ;;
  --functions)
    roles=("${roles[@]}" "roles/cloudfunctions.invoker")
    ;;
  *)
    echo "unknown parameter: $1"
    exit 1
    ;;
  esac
  shift
done

[[ -z "$NAME" ]] && echo "error: require name" && exit 1
[[ -z "$PROJECT_ID" ]] && echo "error: require project ID" && exit 1
[[ -z "$roles" ]] && echo "warning: no role for service account"

# check project id exists
if ! gcloud projects list | awk '{ print $1 }' | grep -Eq "^${PROJECT_ID}$"; then
  echo "error: invalid project ID" && exit 1
fi

SA=$NAME@${PROJECT_ID}.iam.gserviceaccount.com

set -e
if ! gcloud iam service-accounts describe "$SA"; then
  echo "creating service account $SA"
  gcloud iam service-accounts create "$NAME" \
    --description="$DESCRIPTION" \
    --display-name="$NAME" &>/dev/null
else
  echo "service account already existed"
fi

for role in "${roles[@]}"; do
  echo "adding role: $role"
  gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:$SA" \
    --role="$role" &>/dev/null
done

if [[ "$KEY" == "true" ]]; then
  gcloud iam service-accounts keys create $(dirname $0)/../key.json --iam-account "$SA"
fi
