#!/usr/bin/env bash

NAME="$1"
REGION="$2"

[[ -z "$NAME" ]] && echo "error: require NAME" && echo "usage: create-redis-instance NAME REGION" exit 1
[[ -z "$REGION" ]] && echo "error: require REGION" && echo "usage: create-redis-instance NAME REGION" && exit 1

gcloud redis instances delete $NAME --region=$REGION
