#!/usr/bin/env bash

ENDPOINT="$1"
ID_TOKEN="$2"

[[ -z "$ENDPOINT" ]] && echo "error: require ENDPOINT" && echo "usage: loadtest-customer-api ENDPOINT ID_TOKEN" && exit 1
[[ -z "$ID_TOKEN" ]] && echo "error: require ID_TOKEN" && echo "usage: loadtest-customer-api ENDPOINT ID_TOKEN" && exit 1

for i in {1..1000}; do
  curl -XGET "$ENDPOINT" -H "Authorization: Bearer $1" &
done
